// Generated by gencpp from file motoman_msgs/CmdJointTrajectoryEx.msg
// DO NOT EDIT!


#ifndef MOTOMAN_MSGS_MESSAGE_CMDJOINTTRAJECTORYEX_H
#define MOTOMAN_MSGS_MESSAGE_CMDJOINTTRAJECTORYEX_H

#include <ros/service_traits.h>


#include <motoman_msgs/CmdJointTrajectoryExRequest.h>
#include <motoman_msgs/CmdJointTrajectoryExResponse.h>


namespace motoman_msgs
{

struct CmdJointTrajectoryEx
{

typedef CmdJointTrajectoryExRequest Request;
typedef CmdJointTrajectoryExResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CmdJointTrajectoryEx
} // namespace motoman_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motoman_msgs::CmdJointTrajectoryEx > {
  static const char* value()
  {
    return "2c13063e3bd4783949860a7cb1a82ea9";
  }

  static const char* value(const ::motoman_msgs::CmdJointTrajectoryEx&) { return value(); }
};

template<>
struct DataType< ::motoman_msgs::CmdJointTrajectoryEx > {
  static const char* value()
  {
    return "motoman_msgs/CmdJointTrajectoryEx";
  }

  static const char* value(const ::motoman_msgs::CmdJointTrajectoryEx&) { return value(); }
};


// service_traits::MD5Sum< ::motoman_msgs::CmdJointTrajectoryExRequest> should match
// service_traits::MD5Sum< ::motoman_msgs::CmdJointTrajectoryEx >
template<>
struct MD5Sum< ::motoman_msgs::CmdJointTrajectoryExRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::CmdJointTrajectoryEx >::value();
  }
  static const char* value(const ::motoman_msgs::CmdJointTrajectoryExRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::CmdJointTrajectoryExRequest> should match
// service_traits::DataType< ::motoman_msgs::CmdJointTrajectoryEx >
template<>
struct DataType< ::motoman_msgs::CmdJointTrajectoryExRequest>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::CmdJointTrajectoryEx >::value();
  }
  static const char* value(const ::motoman_msgs::CmdJointTrajectoryExRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motoman_msgs::CmdJointTrajectoryExResponse> should match
// service_traits::MD5Sum< ::motoman_msgs::CmdJointTrajectoryEx >
template<>
struct MD5Sum< ::motoman_msgs::CmdJointTrajectoryExResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::CmdJointTrajectoryEx >::value();
  }
  static const char* value(const ::motoman_msgs::CmdJointTrajectoryExResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::CmdJointTrajectoryExResponse> should match
// service_traits::DataType< ::motoman_msgs::CmdJointTrajectoryEx >
template<>
struct DataType< ::motoman_msgs::CmdJointTrajectoryExResponse>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::CmdJointTrajectoryEx >::value();
  }
  static const char* value(const ::motoman_msgs::CmdJointTrajectoryExResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOMAN_MSGS_MESSAGE_CMDJOINTTRAJECTORYEX_H
