// Generated by gencpp from file motoman_msgs/ReadGroupIO.msg
// DO NOT EDIT!


#ifndef MOTOMAN_MSGS_MESSAGE_READGROUPIO_H
#define MOTOMAN_MSGS_MESSAGE_READGROUPIO_H

#include <ros/service_traits.h>


#include <motoman_msgs/ReadGroupIORequest.h>
#include <motoman_msgs/ReadGroupIOResponse.h>


namespace motoman_msgs
{

struct ReadGroupIO
{

typedef ReadGroupIORequest Request;
typedef ReadGroupIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadGroupIO
} // namespace motoman_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motoman_msgs::ReadGroupIO > {
  static const char* value()
  {
    return "03d3163d23ccb5ce5e6b4c3d424efed3";
  }

  static const char* value(const ::motoman_msgs::ReadGroupIO&) { return value(); }
};

template<>
struct DataType< ::motoman_msgs::ReadGroupIO > {
  static const char* value()
  {
    return "motoman_msgs/ReadGroupIO";
  }

  static const char* value(const ::motoman_msgs::ReadGroupIO&) { return value(); }
};


// service_traits::MD5Sum< ::motoman_msgs::ReadGroupIORequest> should match
// service_traits::MD5Sum< ::motoman_msgs::ReadGroupIO >
template<>
struct MD5Sum< ::motoman_msgs::ReadGroupIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::ReadGroupIO >::value();
  }
  static const char* value(const ::motoman_msgs::ReadGroupIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::ReadGroupIORequest> should match
// service_traits::DataType< ::motoman_msgs::ReadGroupIO >
template<>
struct DataType< ::motoman_msgs::ReadGroupIORequest>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::ReadGroupIO >::value();
  }
  static const char* value(const ::motoman_msgs::ReadGroupIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motoman_msgs::ReadGroupIOResponse> should match
// service_traits::MD5Sum< ::motoman_msgs::ReadGroupIO >
template<>
struct MD5Sum< ::motoman_msgs::ReadGroupIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::ReadGroupIO >::value();
  }
  static const char* value(const ::motoman_msgs::ReadGroupIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::ReadGroupIOResponse> should match
// service_traits::DataType< ::motoman_msgs::ReadGroupIO >
template<>
struct DataType< ::motoman_msgs::ReadGroupIOResponse>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::ReadGroupIO >::value();
  }
  static const char* value(const ::motoman_msgs::ReadGroupIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOMAN_MSGS_MESSAGE_READGROUPIO_H
