// Generated by gencpp from file motoman_msgs/ReadSingleIO.msg
// DO NOT EDIT!


#ifndef MOTOMAN_MSGS_MESSAGE_READSINGLEIO_H
#define MOTOMAN_MSGS_MESSAGE_READSINGLEIO_H

#include <ros/service_traits.h>


#include <motoman_msgs/ReadSingleIORequest.h>
#include <motoman_msgs/ReadSingleIOResponse.h>


namespace motoman_msgs
{

struct ReadSingleIO
{

typedef ReadSingleIORequest Request;
typedef ReadSingleIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadSingleIO
} // namespace motoman_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motoman_msgs::ReadSingleIO > {
  static const char* value()
  {
    return "46cc8843a2b05da36149122d04a523ad";
  }

  static const char* value(const ::motoman_msgs::ReadSingleIO&) { return value(); }
};

template<>
struct DataType< ::motoman_msgs::ReadSingleIO > {
  static const char* value()
  {
    return "motoman_msgs/ReadSingleIO";
  }

  static const char* value(const ::motoman_msgs::ReadSingleIO&) { return value(); }
};


// service_traits::MD5Sum< ::motoman_msgs::ReadSingleIORequest> should match
// service_traits::MD5Sum< ::motoman_msgs::ReadSingleIO >
template<>
struct MD5Sum< ::motoman_msgs::ReadSingleIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::ReadSingleIO >::value();
  }
  static const char* value(const ::motoman_msgs::ReadSingleIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::ReadSingleIORequest> should match
// service_traits::DataType< ::motoman_msgs::ReadSingleIO >
template<>
struct DataType< ::motoman_msgs::ReadSingleIORequest>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::ReadSingleIO >::value();
  }
  static const char* value(const ::motoman_msgs::ReadSingleIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motoman_msgs::ReadSingleIOResponse> should match
// service_traits::MD5Sum< ::motoman_msgs::ReadSingleIO >
template<>
struct MD5Sum< ::motoman_msgs::ReadSingleIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::ReadSingleIO >::value();
  }
  static const char* value(const ::motoman_msgs::ReadSingleIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::ReadSingleIOResponse> should match
// service_traits::DataType< ::motoman_msgs::ReadSingleIO >
template<>
struct DataType< ::motoman_msgs::ReadSingleIOResponse>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::ReadSingleIO >::value();
  }
  static const char* value(const ::motoman_msgs::ReadSingleIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOMAN_MSGS_MESSAGE_READSINGLEIO_H
