// Generated by gencpp from file motoman_msgs/WriteSingleIORequest.msg
// DO NOT EDIT!


#ifndef MOTOMAN_MSGS_MESSAGE_WRITESINGLEIOREQUEST_H
#define MOTOMAN_MSGS_MESSAGE_WRITESINGLEIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motoman_msgs
{
template <class ContainerAllocator>
struct WriteSingleIORequest_
{
  typedef WriteSingleIORequest_<ContainerAllocator> Type;

  WriteSingleIORequest_()
    : address(0)
    , value(0)  {
    }
  WriteSingleIORequest_(const ContainerAllocator& _alloc)
    : address(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef uint32_t _address_type;
  _address_type address;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct WriteSingleIORequest_

typedef ::motoman_msgs::WriteSingleIORequest_<std::allocator<void> > WriteSingleIORequest;

typedef boost::shared_ptr< ::motoman_msgs::WriteSingleIORequest > WriteSingleIORequestPtr;
typedef boost::shared_ptr< ::motoman_msgs::WriteSingleIORequest const> WriteSingleIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator1> & lhs, const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator1> & lhs, const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motoman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01af3c84d8b155b2e313c831de55f80d";
  }

  static const char* value(const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01af3c84d8b155b2ULL;
  static const uint64_t static_value2 = 0xe313c831de55f80dULL;
};

template<class ContainerAllocator>
struct DataType< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motoman_msgs/WriteSingleIORequest";
  }

  static const char* value(const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Write 'value' to the IO element at 'address'.\n"
"#\n"
"# This service does not return anything.\n"
"#\n"
"# Addresses are plain, base-10 integers, as used and displayed by the controller\n"
"# (on the teach pendant for instance).\n"
"#\n"
"# Only the following addresses can be written to:\n"
"#\n"
"#  - 27010 and up : Network Inputs (25010 and up on DX100 and FS100)\n"
"#  - 10010 and up : Universal/General Outputs\n"
"#\n"
"# Refer also the Yaskawa Motoman documentation on IO addressing and\n"
"# configuration.\n"
"\n"
"uint32 address\n"
"int32 value\n"
;
  }

  static const char* value(const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteSingleIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator>& v)
  {
    s << indent << "address: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.address);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOMAN_MSGS_MESSAGE_WRITESINGLEIOREQUEST_H
