// Generated by gencpp from file motoman_msgs/WriteMRegister.msg
// DO NOT EDIT!


#ifndef MOTOMAN_MSGS_MESSAGE_WRITEMREGISTER_H
#define MOTOMAN_MSGS_MESSAGE_WRITEMREGISTER_H

#include <ros/service_traits.h>


#include <motoman_msgs/WriteMRegisterRequest.h>
#include <motoman_msgs/WriteMRegisterResponse.h>


namespace motoman_msgs
{

struct WriteMRegister
{

typedef WriteMRegisterRequest Request;
typedef WriteMRegisterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteMRegister
} // namespace motoman_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motoman_msgs::WriteMRegister > {
  static const char* value()
  {
    return "6b8bb3bb740ab645ad65c2abec91e614";
  }

  static const char* value(const ::motoman_msgs::WriteMRegister&) { return value(); }
};

template<>
struct DataType< ::motoman_msgs::WriteMRegister > {
  static const char* value()
  {
    return "motoman_msgs/WriteMRegister";
  }

  static const char* value(const ::motoman_msgs::WriteMRegister&) { return value(); }
};


// service_traits::MD5Sum< ::motoman_msgs::WriteMRegisterRequest> should match
// service_traits::MD5Sum< ::motoman_msgs::WriteMRegister >
template<>
struct MD5Sum< ::motoman_msgs::WriteMRegisterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::WriteMRegister >::value();
  }
  static const char* value(const ::motoman_msgs::WriteMRegisterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::WriteMRegisterRequest> should match
// service_traits::DataType< ::motoman_msgs::WriteMRegister >
template<>
struct DataType< ::motoman_msgs::WriteMRegisterRequest>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::WriteMRegister >::value();
  }
  static const char* value(const ::motoman_msgs::WriteMRegisterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motoman_msgs::WriteMRegisterResponse> should match
// service_traits::MD5Sum< ::motoman_msgs::WriteMRegister >
template<>
struct MD5Sum< ::motoman_msgs::WriteMRegisterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::WriteMRegister >::value();
  }
  static const char* value(const ::motoman_msgs::WriteMRegisterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::WriteMRegisterResponse> should match
// service_traits::DataType< ::motoman_msgs::WriteMRegister >
template<>
struct DataType< ::motoman_msgs::WriteMRegisterResponse>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::WriteMRegister >::value();
  }
  static const char* value(const ::motoman_msgs::WriteMRegisterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOMAN_MSGS_MESSAGE_WRITEMREGISTER_H
