// Generated by gencpp from file motoman_msgs/WriteMRegisterRequest.msg
// DO NOT EDIT!


#ifndef MOTOMAN_MSGS_MESSAGE_WRITEMREGISTERREQUEST_H
#define MOTOMAN_MSGS_MESSAGE_WRITEMREGISTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motoman_msgs
{
template <class ContainerAllocator>
struct WriteMRegisterRequest_
{
  typedef WriteMRegisterRequest_<ContainerAllocator> Type;

  WriteMRegisterRequest_()
    : address(0)
    , value(0)  {
    }
  WriteMRegisterRequest_(const ContainerAllocator& _alloc)
    : address(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef uint32_t _address_type;
  _address_type address;

   typedef uint16_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WriteMRegisterRequest_

typedef ::motoman_msgs::WriteMRegisterRequest_<std::allocator<void> > WriteMRegisterRequest;

typedef boost::shared_ptr< ::motoman_msgs::WriteMRegisterRequest > WriteMRegisterRequestPtr;
typedef boost::shared_ptr< ::motoman_msgs::WriteMRegisterRequest const> WriteMRegisterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator1> & lhs, const ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator1> & lhs, const ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motoman_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5343d995d764283727c41eb509727e5f";
  }

  static const char* value(const ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5343d995d7642837ULL;
  static const uint64_t static_value2 = 0x27c41eb509727e5fULL;
};

template<class ContainerAllocator>
struct DataType< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motoman_msgs/WriteMRegisterRequest";
  }

  static const char* value(const ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Write 'value' to the M register at 'address'.\n"
"#\n"
"# Addresses are plain, base-10 integers, as used and displayed by the controller\n"
"# (on the teach pendant for instance).\n"
"#\n"
"# Only the following addresses can be written to:\n"
"#\n"
"#  - 0 to 559\n"
"#\n"
"# NOTE 1: do not add 1000000 to the address, MotoROS will do this when\n"
"#         necessary.\n"
"#\n"
"# NOTE 2: many programming languages will parse literals starting with '0' as\n"
"#         octal numbers. Do not add leading zeros to register addresses to avoid\n"
"#         specifying the wrong register to write to.\n"
"#\n"
"# Refer also the Yaskawa Motoman documentation on IO addressing and\n"
"# configuration.\n"
"\n"
"uint32 address\n"
"uint16 value\n"
;
  }

  static const char* value(const ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteMRegisterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motoman_msgs::WriteMRegisterRequest_<ContainerAllocator>& v)
  {
    s << indent << "address: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.address);
    s << indent << "value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOMAN_MSGS_MESSAGE_WRITEMREGISTERREQUEST_H
