// Generated by gencpp from file motoman_msgs/WriteGroupIO.msg
// DO NOT EDIT!


#ifndef MOTOMAN_MSGS_MESSAGE_WRITEGROUPIO_H
#define MOTOMAN_MSGS_MESSAGE_WRITEGROUPIO_H

#include <ros/service_traits.h>


#include <motoman_msgs/WriteGroupIORequest.h>
#include <motoman_msgs/WriteGroupIOResponse.h>


namespace motoman_msgs
{

struct WriteGroupIO
{

typedef WriteGroupIORequest Request;
typedef WriteGroupIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteGroupIO
} // namespace motoman_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motoman_msgs::WriteGroupIO > {
  static const char* value()
  {
    return "442d77ce292ab13600e884d7860398a9";
  }

  static const char* value(const ::motoman_msgs::WriteGroupIO&) { return value(); }
};

template<>
struct DataType< ::motoman_msgs::WriteGroupIO > {
  static const char* value()
  {
    return "motoman_msgs/WriteGroupIO";
  }

  static const char* value(const ::motoman_msgs::WriteGroupIO&) { return value(); }
};


// service_traits::MD5Sum< ::motoman_msgs::WriteGroupIORequest> should match
// service_traits::MD5Sum< ::motoman_msgs::WriteGroupIO >
template<>
struct MD5Sum< ::motoman_msgs::WriteGroupIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::WriteGroupIO >::value();
  }
  static const char* value(const ::motoman_msgs::WriteGroupIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::WriteGroupIORequest> should match
// service_traits::DataType< ::motoman_msgs::WriteGroupIO >
template<>
struct DataType< ::motoman_msgs::WriteGroupIORequest>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::WriteGroupIO >::value();
  }
  static const char* value(const ::motoman_msgs::WriteGroupIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motoman_msgs::WriteGroupIOResponse> should match
// service_traits::MD5Sum< ::motoman_msgs::WriteGroupIO >
template<>
struct MD5Sum< ::motoman_msgs::WriteGroupIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motoman_msgs::WriteGroupIO >::value();
  }
  static const char* value(const ::motoman_msgs::WriteGroupIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motoman_msgs::WriteGroupIOResponse> should match
// service_traits::DataType< ::motoman_msgs::WriteGroupIO >
template<>
struct DataType< ::motoman_msgs::WriteGroupIOResponse>
{
  static const char* value()
  {
    return DataType< ::motoman_msgs::WriteGroupIO >::value();
  }
  static const char* value(const ::motoman_msgs::WriteGroupIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOMAN_MSGS_MESSAGE_WRITEGROUPIO_H
